name: Pull Request

on:
  pull_request:

jobs:
  tests:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Install dependencies
        run: |
          sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer
          sudo xcodebuild -license accept

      - name: Run Tests
        run: xcodebuild -scheme ProjectCI -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' -resultBundlePath ./test_result -enableCodeCoverage YES -derivedDataPath . clean build test

      - name: Code coverage
        run: |
          bash xccov-to-sonarqube-generic.sh test_result.xcresult/ >coverage.xml

      - name: Install SonarScanner
        run: |
          brew install sonar-scanner

      - name: SonarCloud Analysis
        run: |
          sonar-scanner \
            -Dsonar.organization={org} \
            -Dsonar.projectKey={project_key} \
            -Dsonar.sources=Sources/ \
            -Dsonar.tests=Tests/ \
            -Dsonar.language=swift \
            -Dsonar.sourceEncoding=UTF-8 \
            -Dsonar.verbose=true \
            -Dsonar.coverageReportPaths=coverage.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}