name: Pull Request

on:
  pull_request:

jobs:
  tests:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Accept Xcode license and switch version
        run: |
          sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer
          sudo xcodebuild -license accept

      - name: Run Unit Tests with Code Coverage
        run: |
          xcodebuild \
            -scheme ClockSnd \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
            -resultBundlePath ./test_result \
            -enableCodeCoverage YES \
            -derivedDataPath . \
            clean build test

      - name: Generate Coverage Report
        run: |
          chmod +x xccov-to-sonarqube-generic.sh
          ./xccov-to-sonarqube-generic.sh test_result.xcresult > coverage.xml

      - name: Install SonarScanner
        run: brew install sonar-scanner

      - name: Run SonarCloud Analysis
        run: sonar-scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
