name: Pull Request

on:
  pull_request:

jobs:
  build-and-analyze:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Accept Xcode license and switch version
        run: |
          sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer
          sudo xcodebuild -license accept

      - name: Build for iOS Simulator (no signing, no tests)
        run: |
          xcodebuild \
            -scheme ClockSnd \  # Replace with your actual scheme
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
            -resultBundlePath ./build_result \
            -derivedDataPath . \
            clean build

      - name: Install SonarScanner
        run: brew install sonar-scanner

      - name: Run SonarCloud Analysis
        run: sonar-scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}